# **About Dataset**
## This dataset contains 5 different CSV files representing distinct categories of e-commerce data. Below is a comprehensive Python notebook detailing the data cleaning pipiline using Google Colab and Pandas.

In [78]:
import pandas as pd
from google.colab import files

# **1.Cleaning Process for Women clothing data(CSV)**

In [18]:
# loading csv file of womens_clothing
path='/content/drive/MyDrive/e-commerce dataset/us-shein-womens_clothing-4620.csv'
data=pd.read_csv(path,encoding='latin-1')
data.head()

,product-locatelabels-img src,color-count,goods-title-link,rank-title,rank-sub,price,discount,selling_proposition
0,https://img.ltwebstatic.com/images3_pi/2024/02...,6.0,SHEIN SXY Women's Solid Color Backless Tie Nec...,#1 Best Seller,In Sexy Women Apparel,$12.19,NaN,NaN
1,NaN,4.0,Knitted Color-Block Striped Hollow Out Short-S...,#6 Best Seller,In Short Sleeve Women Clothing,$16.59,-14%,NaN
2,NaN,7.0,Hollow Out Knit Crop Sweater With Bell Sleeve,#2 Best Sellers,in Women Sweaters,$9.19,-13%,NaN
3,https://img.shein.com/images3/2024/04/30/0e/17...,9.0,SHEIN EZwear Women's Short Sleeve T-Shirt And ...,NaN,NaN,$14.29,NaN,10k+ sold recently
4,https://img.ltwebstatic.com/images3_pi/2024/02...,NaN,SHEIN SXY Solid Color Zipper Half Front Fashio...,NaN,NaN,$14.84,-8%,1.5k+ sold recently

In [19]:
data.info()# initial data information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4619 entries, 0 to 4618
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   product-locatelabels-img src  3622 non-null   object
 1   color-count                   2415 non-null   float64
 2   goods-title-link              4619 non-null   object
 3   rank-title                    1056 non-null   object
 4   rank-sub                      1056 non-null   object
 5   price                         4619 non-null   object
 6   discount                      2752 non-null   object
 7   selling_proposition           3452 non-null   object
dtypes: float64(1), object(7)
memory usage: 288.8+ KB

In [49]:
# let's first rename the column name to look professional
df_cleaned=data.rename(columns={'goods-title-link':'product_name',
                                'color-count':'available_color',
                                'selling_proposition':'tagline',
                                'product-locatelabels-img src':'image_url'}).copy()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4432 entries, 0 to 4431
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump href  38 non-null     object
 1   tagline                      3501 non-null   object
 2   price                        4432 non-null   object
 3   discount                     2799 non-null   object
 4   available_color              1091 non-null   float64
 5   product_title                4432 non-null   object
dtypes: float64(1), object(5)
memory usage: 207.9+ KB

In [21]:
# Now change the data type of price and discount for analysis
if 'price' in df_cleaned.columns:
  df_cleaned['price']=df_cleaned['price'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['price']=pd.to_numeric(df_cleaned['price'],errors='coerce')

In [22]:
# Now change the data type of discount
if 'discount' in df_cleaned.columns:
  df_cleaned['discount']=df_cleaned['discount'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['discount']=pd.to_numeric(df_cleaned['discount'],errors='coerce')

In [23]:
# Now fill missing discount with 0 means no discount
df_cleaned['discount']=df_cleaned['discount'].fillna(0)

In [24]:
# Now fill missing available_color with 1 means assuming at least the default color
df_cleaned['available_color']=df_cleaned['available_color'].fillna(1)

In [25]:
# Now add our trekking categoris for the master dataset later
df_cleaned['main_category']="Women's Clothing"

In [26]:
# Now let's check
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4619 entries, 0 to 4618
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   image_url        3622 non-null   object
 1   available_color  4619 non-null   float64
 2   product_name     4619 non-null   object
 3   rank-title       1056 non-null   object
 4   rank-sub         1056 non-null   object
 5   price            4619 non-null   float64
 6   discount         4619 non-null   float64
 7   tagline          3452 non-null   object
 8   main_category    4619 non-null   object
dtypes: float64(3), object(6)
memory usage: 324.9+ KB

In [27]:
df_cleaned.head()

,image_url,available_color,product_name,rank-title,rank-sub,price,discount,tagline,main_category
0,https://img.ltwebstatic.com/images3_pi/2024/02...,6.0,SHEIN SXY Women's Solid Color Backless Tie Nec...,#1 Best Seller,In Sexy Women Apparel,12.19,0.0,NaN,Women's Clothing
1,NaN,4.0,Knitted Color-Block Striped Hollow Out Short-S...,#6 Best Seller,In Short Sleeve Women Clothing,16.59,14.0,NaN,Women's Clothing
2,NaN,7.0,Hollow Out Knit Crop Sweater With Bell Sleeve,#2 Best Sellers,in Women Sweaters,9.19,13.0,NaN,Women's Clothing
3,https://img.shein.com/images3/2024/04/30/0e/17...,9.0,SHEIN EZwear Women's Short Sleeve T-Shirt And ...,NaN,NaN,14.29,0.0,10k+ sold recently,Women's Clothing
4,https://img.ltwebstatic.com/images3_pi/2024/02...,1.0,SHEIN SXY Solid Color Zipper Half Front Fashio...,NaN,NaN,14.84,8.0,1.5k+ sold recently,Women's Clothing

In [81]:
df_cleaned.to_csv('clean_womens_clothing_data.csv',index=False)
files.download('clean_womens_clothing_data.csv')

# **2.Cleaning Proceses for Mens Clothing data(CSV)**

In [28]:
# import data
path='/content/drive/MyDrive/e-commerce dataset/us-shein-mens_clothes-1891.csv'
data=pd.read_csv(path,encoding='latin-1')
data.head()

,color-count,goods-title-link,selling_proposition,price,discount,rank-title,rank-sub
0,15.0,Manfinity Homme Loose Fit Men's Solid Color Bu...,10k+ sold recently,$11.99,-7%,NaN,NaN
1,NaN,Manfinity Joysei Men's Star Patterned Shorts W...,NaN,$11.19,-13%,#8 Best Seller,in Blue Men Clothing
2,NaN,Men's Summer Casual Short Sleeve T-Shirt With ...,NaN,$8.09,-13%,#10 Best Seller,in Figure Men T-Shirts
3,11.0,Manfinity Homme Men's Contrast Color Short Sle...,10k+ sold recently,$9.99,-12%,NaN,NaN
4,7.0,Manfinity EMRG Loose Fit Men Plus Letter Print...,30+ sold recently,$3.48,-70%,NaN,NaN

In [29]:
# data info before cleaning
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   color-count          1141 non-null   float64
 1   goods-title-link     1889 non-null   object
 2   selling_proposition  1277 non-null   object
 3   price                1889 non-null   object
 4   discount             1860 non-null   object
 5   rank-title           560 non-null    object
 6   rank-sub             560 non-null    object
dtypes: float64(1), object(6)
memory usage: 103.5+ KB

In [106]:
# First change the column name for professinal
df_cleaned=data.rename(columns={'color-count':'available_color',
                                'goods-title-link':'product_name',
                                'rank-title':'rank_title',
                                'rank-sub':'rank_sub'}).copy()

In [31]:
# Now change datatype of price for easy analysis
if 'price' in df_cleaned.columns:
  df_cleaned['price']=df_cleaned['price'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['price']=pd.to_numeric(df_cleaned['price'],errors='coerce')

In [32]:
# Now change datatype of discount for analysis
if 'discount' in df_cleaned.columns:
  df_cleaned['discount']=df_cleaned['discount'].astype(str).str.replace(r'^\d.','',regex=True)
  df_cleaned['discount']=pd.to_numeric(df_cleaned['discount'],errors='coerce')

In [33]:
# now fill available color assuming default color with 1
df_cleaned['available_color']=df_cleaned['available_color'].fillna(1)

In [34]:
# Noe fill discount with 0 assuming no discount
df_cleaned['discount']=df_cleaned['discount'].fillna(0)

In [35]:
# Now add a column as main category with value mens cloting
df_cleaned['main_category']="Men's Clothing"

In [36]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1890 entries, 0 to 1889
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   available_color      1890 non-null   float64
 1   product_name         1889 non-null   object
 2   selling_proposition  1277 non-null   object
 3   price                1889 non-null   float64
 4   discount             1890 non-null   float64
 5   rank_title           560 non-null    object
 6   rank_sub             560 non-null    object
 7   main_category        1890 non-null   object
dtypes: float64(3), object(5)
memory usage: 118.3+ KB

In [38]:
df_cleaned.head()

,available_color,product_name,selling_proposition,price,discount,rank_title,rank_sub,main_category
0,15.0,Manfinity Homme Loose Fit Men's Solid Color Bu...,10k+ sold recently,11.99,0.0,NaN,NaN,Men's Clothing
1,1.0,Manfinity Joysei Men's Star Patterned Shorts W...,NaN,11.19,0.0,#8 Best Seller,in Blue Men Clothing,Men's Clothing
2,1.0,Men's Summer Casual Short Sleeve T-Shirt With ...,NaN,8.09,0.0,#10 Best Seller,in Figure Men T-Shirts,Men's Clothing
3,11.0,Manfinity Homme Men's Contrast Color Short Sle...,10k+ sold recently,9.99,0.0,NaN,NaN,Men's Clothing
4,7.0,Manfinity EMRG Loose Fit Men Plus Letter Print...,30+ sold recently,3.48,0.0,NaN,NaN,Men's Clothing

In [82]:
df_cleaned.to_csv('clean_mens_clothing_data.csv',index=False)
files.download('clean_mens_clothing_data.csv')

# **3. Cleaning Proceses for Baby and Maternity data(CSV)**

In [39]:
path='/content/drive/MyDrive/e-commerce dataset/us-shein-baby_and_maternity-4433.csv'
data=pd.read_csv(path,encoding='latin-1')
data.head()

,goods-title-link--jump,goods-title-link--jump href,selling_proposition,price,discount,color-count,goods-title-link
0,Baby Boys' Dinosaur Printed Vest And Letter Pr...,https://us.shein.com/Baby-Boys-Dinosaur-Printe...,70+ sold recently,$2.55,-50%,NaN,NaN
1,Baby Boy 3D Ear Design Hooded Belted Flannel Robe,https://us.shein.com/Baby-Boy-3D-Ear-Design-Ho...,NaN,$6.80,-16%,NaN,NaN
2,Baby Girl Floral Print Cami Dress,https://us.shein.com/Baby-Girl-Floral-Print-Ca...,400+ sold recently,$3.95,-16%,NaN,NaN
3,Baby Girl's Casual And Simple Flower Printed S...,https://us.shein.com/Baby-Girl-s-Casual-And-Si...,500+ sold recently,$6.37,-17%,4.0,NaN
4,Baby Girl Letter Graphic Tie Dye Hoodie With S...,https://us.shein.com/Baby-Girl-Letter-Graphic-...,100+ sold recently,$8.00,-25%,NaN,NaN

In [40]:
data.info() # before cleaning

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4432 entries, 0 to 4431
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       38 non-null     object
 1   goods-title-link--jump href  38 non-null     object
 2   selling_proposition          3501 non-null   object
 3   price                        4432 non-null   object
 4   discount                     2799 non-null   object
 5   color-count                  1091 non-null   float64
 6   goods-title-link             4394 non-null   object
dtypes: float64(1), object(6)
memory usage: 242.5+ KB

In [44]:
# first merge column goods title link jump and goods title link as product title
data['product_title']=data['goods-title-link--jump'].fillna(data['goods-title-link'])
data.head()

,goods-title-link--jump,goods-title-link--jump href,selling_proposition,price,discount,color-count,goods-title-link,product_title
0,Baby Boys' Dinosaur Printed Vest And Letter Pr...,https://us.shein.com/Baby-Boys-Dinosaur-Printe...,70+ sold recently,$2.55,-50%,NaN,NaN,Baby Boys' Dinosaur Printed Vest And Letter Pr...
1,Baby Boy 3D Ear Design Hooded Belted Flannel Robe,https://us.shein.com/Baby-Boy-3D-Ear-Design-Ho...,NaN,$6.80,-16%,NaN,NaN,Baby Boy 3D Ear Design Hooded Belted Flannel Robe
2,Baby Girl Floral Print Cami Dress,https://us.shein.com/Baby-Girl-Floral-Print-Ca...,400+ sold recently,$3.95,-16%,NaN,NaN,Baby Girl Floral Print Cami Dress
3,Baby Girl's Casual And Simple Flower Printed S...,https://us.shein.com/Baby-Girl-s-Casual-And-Si...,500+ sold recently,$6.37,-17%,4.0,NaN,Baby Girl's Casual And Simple Flower Printed S...
4,Baby Girl Letter Graphic Tie Dye Hoodie With S...,https://us.shein.com/Baby-Girl-Letter-Graphic-...,100+ sold recently,$8.00,-25%,NaN,NaN,Baby Girl Letter Graphic Tie Dye Hoodie With S...

In [46]:
# now drop the useless columns
columns_to_drop=['goods-title-link--jump','goods-title-link']
data=data.drop(columns=[col for col in columns_to_drop if col in data.columns])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4432 entries, 0 to 4431
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump href  38 non-null     object
 1   selling_proposition          3501 non-null   object
 2   price                        4432 non-null   object
 3   discount                     2799 non-null   object
 4   color-count                  1091 non-null   float64
 5   product_title                4432 non-null   object
dtypes: float64(1), object(5)
memory usage: 207.9+ KB

In [50]:
# Now change the columns name for analysis
df_cleaned=data.rename(columns={'color-count':'available_color',
                                'goods-title-link--jump href':'title_href'}).copy()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4432 entries, 0 to 4431
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title_href           38 non-null     object
 1   selling_proposition  3501 non-null   object
 2   price                4432 non-null   object
 3   discount             2799 non-null   object
 4   available_color      1091 non-null   float64
 5   product_title        4432 non-null   object
dtypes: float64(1), object(5)
memory usage: 207.9+ KB

In [56]:
#Now change the data type of available color as float to numeric
if 'available_color' in df_cleaned.columns:
  df_cleaned['available_color']=pd.to_numeric(df_cleaned['available_color'])

In [53]:
# Now change the data type of price and discount for analysis
if 'price' in df_cleaned.columns:
  df_cleaned['price']=df_cleaned['price'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['price']=pd.to_numeric(df_cleaned['price'],errors='coerce')
# Now change the data type of discount
if 'discount' in df_cleaned.columns:
  df_cleaned['discount']=df_cleaned['discount'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['discount']=pd.to_numeric(df_cleaned['discount'],errors='coerce')

# Now fill missing discount with 0 means no discount
df_cleaned['discount']=df_cleaned['discount'].fillna(0)

# Now fill missing available_color with 1 means assuming at least the default color
df_cleaned['available_color']=df_cleaned['available_color'].fillna(1)

# Now add our trekking categoris for the master dataset later
df_cleaned['main_category']="Baby & Maternity"

In [57]:
df_cleaned.head()

,title_href,selling_proposition,price,discount,available_color,product_title,main_category
0,https://us.shein.com/Baby-Boys-Dinosaur-Printe...,70+ sold recently,2.55,50.0,1.0,Baby Boys' Dinosaur Printed Vest And Letter Pr...,Baby & Maternity
1,https://us.shein.com/Baby-Boy-3D-Ear-Design-Ho...,NaN,6.80,16.0,1.0,Baby Boy 3D Ear Design Hooded Belted Flannel Robe,Baby & Maternity
2,https://us.shein.com/Baby-Girl-Floral-Print-Ca...,400+ sold recently,3.95,16.0,1.0,Baby Girl Floral Print Cami Dress,Baby & Maternity
3,https://us.shein.com/Baby-Girl-s-Casual-And-Si...,500+ sold recently,6.37,17.0,4.0,Baby Girl's Casual And Simple Flower Printed S...,Baby & Maternity
4,https://us.shein.com/Baby-Girl-Letter-Graphic-...,100+ sold recently,8.00,25.0,1.0,Baby Girl Letter Graphic Tie Dye Hoodie With S...,Baby & Maternity

In [58]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4432 entries, 0 to 4431
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title_href           38 non-null     object
 1   selling_proposition  3501 non-null   object
 2   price                4432 non-null   float64
 3   discount             4432 non-null   float64
 4   available_color      4432 non-null   float64
 5   product_title        4432 non-null   object
 6   main_category        4432 non-null   object
dtypes: float64(3), object(4)
memory usage: 242.5+ KB

In [83]:
df_cleaned.to_csv('clean_baby&maternity_data.csv',index=False)
files.download('clean_baby&maternity_data.csv')

# **4.Cleaning Proceses for Shoes data(CSV)**

In [59]:
path='/content/drive/MyDrive/e-commerce dataset/us-shein-shoes-4381.csv'
data=pd.read_csv(path,encoding='latin-1')
data.head()

,color-count,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,18.0,"Korean Style Casual Flat Sandals Women Shoes, ...",https://us.shein.com/Korean-Style-Casual-Flat-...,#1 Best Seller,In Beige Women Sandals,$5.25,-50%,NaN,NaN
1,8.0,"Sports Shoes, Street Sports Shoes, Men's And W...",https://us.shein.com/Sports-Shoes-Street-Sport...,#1 Best Seller,In Black and White Men Sneakers,$88.70,-24%,NaN,NaN
2,4.0,"New Style Plush Slippers With Toe, Thick Sole ...",https://us.shein.com/New-Style-Plush-Slippers-...,#1 Best Seller,In Hot Pink Women Home Slippers,$52.70,-21%,NaN,NaN
3,5.0,New Arrival Women's Pointed Toe Shallow Mouth ...,https://us.shein.com/New-Arrival-Women-s-Point...,#2 Best Seller,In Blue Women Pumps,$22.40,-19%,NaN,NaN
4,NaN,"Summer Men's Casual Slippers, Trendy Slippers ...",https://us.shein.com/Summer-Men-s-Casual-Slipp...,#5 Best Seller,In Beige Men Shoes,$3.16,-63%,NaN,NaN

In [60]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4380 entries, 0 to 4379
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   color-count                  2180 non-null   float64
 1   goods-title-link--jump       39 non-null     object
 2   goods-title-link--jump href  39 non-null     object
 3   rank-title                   1274 non-null   object
 4   rank-sub                     1274 non-null   object
 5   price                        4380 non-null   object
 6   discount                     4249 non-null   object
 7   selling_proposition          2799 non-null   object
 8   goods-title-link             4341 non-null   object
dtypes: float64(1), object(8)
memory usage: 308.1+ KB

In [61]:
data.describe()

       color-count
count  2180.000000
mean     10.159633
std       7.115853
min       4.000000
25%       5.000000
50%       7.000000
75%      13.000000
max      39.000000

In [62]:
# first merge column goods title link jump and goods title link as product title
data['product_title']=data['goods-title-link--jump'].fillna(data['goods-title-link'])
data.head()

,color-count,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link,product_title
0,18.0,"Korean Style Casual Flat Sandals Women Shoes, ...",https://us.shein.com/Korean-Style-Casual-Flat-...,#1 Best Seller,In Beige Women Sandals,$5.25,-50%,NaN,NaN,"Korean Style Casual Flat Sandals Women Shoes, ..."
1,8.0,"Sports Shoes, Street Sports Shoes, Men's And W...",https://us.shein.com/Sports-Shoes-Street-Sport...,#1 Best Seller,In Black and White Men Sneakers,$88.70,-24%,NaN,NaN,"Sports Shoes, Street Sports Shoes, Men's And W..."
2,4.0,"New Style Plush Slippers With Toe, Thick Sole ...",https://us.shein.com/New-Style-Plush-Slippers-...,#1 Best Seller,In Hot Pink Women Home Slippers,$52.70,-21%,NaN,NaN,"New Style Plush Slippers With Toe, Thick Sole ..."
3,5.0,New Arrival Women's Pointed Toe Shallow Mouth ...,https://us.shein.com/New-Arrival-Women-s-Point...,#2 Best Seller,In Blue Women Pumps,$22.40,-19%,NaN,NaN,New Arrival Women's Pointed Toe Shallow Mouth ...
4,NaN,"Summer Men's Casual Slippers, Trendy Slippers ...",https://us.shein.com/Summer-Men-s-Casual-Slipp...,#5 Best Seller,In Beige Men Shoes,$3.16,-63%,NaN,NaN,"Summer Men's Casual Slippers, Trendy Slippers ..."

In [63]:
# now drop the useless columns
columns_to_drop=['goods-title-link--jump','goods-title-link']
data=data.drop(columns=[col for col in columns_to_drop if col in data.columns])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4380 entries, 0 to 4379
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   color-count                  2180 non-null   float64
 1   goods-title-link--jump href  39 non-null     object
 2   rank-title                   1274 non-null   object
 3   rank-sub                     1274 non-null   object
 4   price                        4380 non-null   object
 5   discount                     4249 non-null   object
 6   selling_proposition          2799 non-null   object
 7   product_title                4380 non-null   object
dtypes: float64(1), object(7)
memory usage: 273.9+ KB

In [64]:
# Now change the columns name for analysis
df_cleaned=data.rename(columns={'color-count':'available_color',
                                'goods-title-link--jump href':'title_href'}).copy()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4380 entries, 0 to 4379
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   available_color      2180 non-null   float64
 1   title_href           39 non-null     object
 2   rank-title           1274 non-null   object
 3   rank-sub             1274 non-null   object
 4   price                4380 non-null   object
 5   discount             4249 non-null   object
 6   selling_proposition  2799 non-null   object
 7   product_title        4380 non-null   object
dtypes: float64(1), object(7)
memory usage: 273.9+ KB

In [66]:
# Now change the data type of price and discount for analysis
if 'price' in df_cleaned.columns:
  df_cleaned['price']=df_cleaned['price'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['price']=pd.to_numeric(df_cleaned['price'],errors='coerce')
# Now change the data type of discount
if 'discount' in df_cleaned.columns:
  df_cleaned['discount']=df_cleaned['discount'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['discount']=pd.to_numeric(df_cleaned['discount'],errors='coerce')

# Now fill missing discount with 0 means no discount
df_cleaned['discount']=df_cleaned['discount'].fillna(0)

# Now fill missing available_color with 1 means assuming at least the default color
df_cleaned['available_color']=df_cleaned['available_color'].fillna(1)

# Now add our trekking categoris for the master dataset later
df_cleaned['main_category']="Shoes"

In [67]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4380 entries, 0 to 4379
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   available_color      4380 non-null   float64
 1   title_href           39 non-null     object
 2   rank-title           1274 non-null   object
 3   rank-sub             1274 non-null   object
 4   price                4380 non-null   float64
 5   discount             4380 non-null   float64
 6   selling_proposition  2799 non-null   object
 7   product_title        4380 non-null   object
 8   main_category        4380 non-null   object
dtypes: float64(3), object(6)
memory usage: 308.1+ KB

In [69]:
df_cleaned.describe()

       available_color        price     discount
count      4380.000000  4380.000000  4380.000000
mean          5.558904    14.053902    26.922603
std           6.795244    11.083575    14.019452
min           1.000000     0.380000     0.000000
25%           1.000000     8.440000    20.000000
50%           1.000000    12.700000    21.000000
75%           7.000000    19.052500    29.000000
max          39.000000   301.650000    85.000000

In [99]:
# checking for dublicate rows
dubilicate_rows=df_cleaned.duplicated(subset=['product_title','price','rank-title','selling_proposition','discount','rank-sub','available_color']).sum()
print(f"Number of duplicate rows: {dubilicate_rows}")

Number of duplicate rows: 0

In [84]:
df_cleaned.to_csv('clean_shoes_data.csv',index=False)
files.download('clean_shoes_data.csv')

# **5. Cleaning Process for Beauty & Health data(CSV)**

In [70]:
path='/content/drive/MyDrive/e-commerce dataset/us-shein-beauty_and_health-4267.csv'
data=pd.read_csv(path,encoding='latin-1')
data.head()

,goods-title-link--jump,goods-title-link--jump href,selling_proposition,price,discount,color-count,rank-title,rank-sub,goods-title-link
0,90ML 3.0FL.OZ Fragrance Hair & Body Mist Vanil...,https://us.shein.com/90ML-3-0FL-OZ-Fragrance-H...,30+ sold recently,$5.90,-5%,NaN,NaN,NaN,NaN
1,SHEGLAM ColorÂ BloomÂ LiquidÂ BlushÂ MatteÂ Fi...,https://us.shein.com/SHEGLAM-Color-Bloom-Liqui...,NaN,$4.99,-17%,14.0,#2 Best Sellers,in Blush,NaN
2,1pc Silicone Facial Massage Ice Tray,https://us.shein.com/1pc-Silicone-Facial-Massa...,NaN,$2.64,-20%,NaN,#1 Best Sellers,in Facial Massage Tools,NaN
3,5Ml Bottom Refillable Perfume Bottle With Pump...,https://us.shein.com/5Ml-Bottom-Refillable-Per...,5.3k+ sold recently,$1.50,-12%,NaN,NaN,NaN,NaN
4,12pcs Multi-Functional Makeup Brush Set Includ...,https://us.shein.com/12pcs-Multi-Functional-Ma...,NaN,$7.80,-5%,8.0,#2 Best Sellers,in Brushes Sets,NaN

In [71]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4266 entries, 0 to 4265
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       39 non-null     object
 1   goods-title-link--jump href  39 non-null     object
 2   selling_proposition          3257 non-null   object
 3   price                        4266 non-null   object
 4   discount                     3984 non-null   object
 5   color-count                  1206 non-null   float64
 6   rank-title                   838 non-null    object
 7   rank-sub                     838 non-null    object
 8   goods-title-link             4227 non-null   object
dtypes: float64(1), object(8)
memory usage: 300.1+ KB

In [72]:
# first merge column goods title link jump and goods title link as product title
data['product_title']=data['goods-title-link--jump'].fillna(data['goods-title-link'])
data.head()

,goods-title-link--jump,goods-title-link--jump href,selling_proposition,price,discount,color-count,rank-title,rank-sub,goods-title-link,product_title
0,90ML 3.0FL.OZ Fragrance Hair & Body Mist Vanil...,https://us.shein.com/90ML-3-0FL-OZ-Fragrance-H...,30+ sold recently,$5.90,-5%,NaN,NaN,NaN,NaN,90ML 3.0FL.OZ Fragrance Hair & Body Mist Vanil...
1,SHEGLAM ColorÂ BloomÂ LiquidÂ BlushÂ MatteÂ Fi...,https://us.shein.com/SHEGLAM-Color-Bloom-Liqui...,NaN,$4.99,-17%,14.0,#2 Best Sellers,in Blush,NaN,SHEGLAM ColorÂ BloomÂ LiquidÂ BlushÂ MatteÂ Fi...
2,1pc Silicone Facial Massage Ice Tray,https://us.shein.com/1pc-Silicone-Facial-Massa...,NaN,$2.64,-20%,NaN,#1 Best Sellers,in Facial Massage Tools,NaN,1pc Silicone Facial Massage Ice Tray
3,5Ml Bottom Refillable Perfume Bottle With Pump...,https://us.shein.com/5Ml-Bottom-Refillable-Per...,5.3k+ sold recently,$1.50,-12%,NaN,NaN,NaN,NaN,5Ml Bottom Refillable Perfume Bottle With Pump...
4,12pcs Multi-Functional Makeup Brush Set Includ...,https://us.shein.com/12pcs-Multi-Functional-Ma...,NaN,$7.80,-5%,8.0,#2 Best Sellers,in Brushes Sets,NaN,12pcs Multi-Functional Makeup Brush Set Includ...

In [73]:
# now drop the useless columns
columns_to_drop=['goods-title-link--jump','goods-title-link']
data=data.drop(columns=[col for col in columns_to_drop if col in data.columns])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4266 entries, 0 to 4265
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump href  39 non-null     object
 1   selling_proposition          3257 non-null   object
 2   price                        4266 non-null   object
 3   discount                     3984 non-null   object
 4   color-count                  1206 non-null   float64
 5   rank-title                   838 non-null    object
 6   rank-sub                     838 non-null    object
 7   product_title                4266 non-null   object
dtypes: float64(1), object(7)
memory usage: 266.8+ KB

In [74]:
# Now change the columns name for analysis
df_cleaned=data.rename(columns={'color-count':'available_color',
                                'goods-title-link--jump href':'title_href'}).copy()
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4266 entries, 0 to 4265
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title_href           39 non-null     object
 1   selling_proposition  3257 non-null   object
 2   price                4266 non-null   object
 3   discount             3984 non-null   object
 4   available_color      1206 non-null   float64
 5   rank-title           838 non-null    object
 6   rank-sub             838 non-null    object
 7   product_title        4266 non-null   object
dtypes: float64(1), object(7)
memory usage: 266.8+ KB

In [75]:
# Now change the data type of price and discount for analysis
if 'price' in df_cleaned.columns:
  df_cleaned['price']=df_cleaned['price'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['price']=pd.to_numeric(df_cleaned['price'],errors='coerce')
# Now change the data type of discount
if 'discount' in df_cleaned.columns:
  df_cleaned['discount']=df_cleaned['discount'].astype(str).str.replace(r'[^\d.]','',regex=True)
  df_cleaned['discount']=pd.to_numeric(df_cleaned['discount'],errors='coerce')

# Now fill missing discount with 0 means no discount
df_cleaned['discount']=df_cleaned['discount'].fillna(0)

# Now fill missing available_color with 1 means assuming at least the default color
df_cleaned['available_color']=df_cleaned['available_color'].fillna(1)

# Now add our trekking categoris for the master dataset later
df_cleaned['main_category']="Beauty & Health"

In [76]:
df_cleaned.describe()

             price     discount  available_color
count  4266.000000  4266.000000      4266.000000
mean      5.338912    16.225035         3.067042
std      11.075828    17.308266         4.445972
min       0.150000     0.000000         1.000000
25%       1.562500     5.000000         1.000000
50%       2.390000     8.000000         1.000000
75%       4.500000    25.000000         4.000000
max     209.300000    89.000000        36.000000

In [77]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4266 entries, 0 to 4265
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   title_href           39 non-null     object
 1   selling_proposition  3257 non-null   object
 2   price                4266 non-null   float64
 3   discount             4266 non-null   float64
 4   available_color      4266 non-null   float64
 5   rank-title           838 non-null    object
 6   rank-sub             838 non-null    object
 7   product_title        4266 non-null   object
 8   main_category        4266 non-null   object
dtypes: float64(3), object(6)
memory usage: 300.1+ KB

In [100]:
# checking for dublicate rows
dubilicate_rows=df_cleaned.duplicated(subset=['product_title','price','rank-title','selling_proposition','discount','rank-sub','available_color']).sum()
print(f"Number of duplicate rows: {dubilicate_rows}")

Number of duplicate rows: 0

In [95]:
# deleting dublicate rows
df_cleaned=df_cleaned.drop_duplicates(subset=['product_title','price','rank-title','selling_proposition','discount','rank-sub'])

In [85]:
df_cleaned.to_csv('clean_beauty&health_data.csv',index=False)
files.download('clean_beauty&health_data.csv')